# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: 
  vmImage: 'windows-2019'

stages:
  - stage: BuildDBSoln
    jobs: 
    - job: builddb
      displayName: 'Build DB Proj'
      steps:

      - task: VSBuild@1
        inputs:
          solution: '**/*.sqlproj'
          platform: 'Any CPU'
          configuration: 'Release'

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '**\*.dacpac'
          TargetFolder: '$(build.artifactstagingdirectory)'
          flattenFolders: true
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

  # deploy to dev database 
  - stage: devDatabase
    pool: 'Internal Agent Pool'
    displayName: 'Deploy Dev dacpac'
    variables:
    - group: project.Dev.DBDetails
    jobs:
      - deployment: Deploy
        environment: DEV_DB
        strategy:
          runOnce:
            deploy:
              steps:
                 
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'current'
                    artifactName: 'drop'
                    targetPath: '$(System.ArtifactsDirectory)'
                - task: SqlAzureDacpacDeployment@1
                  inputs:
                    azureSubscription: '<name of subscription>'
                    AuthenticationType: 'server' # you can use the service principal option as well 
                    ServerName: '$(DBServerName)'
                    DatabaseName: '$(DBName)'
                    SqlUsername: '$(sqluser)'
                    SqlPassword: '$(sqlpwd)'
                    deployType: 'DacpacTask'
                    DeploymentAction: 'Publish'
                    DacpacFile: '$(System.ArtifactsDirectory)/**/*.dacpac'
                    IpDetectionMethod: 'AutoDetect'
